---
title: "**Homework 3**"
author: "Kevin Ha"
date: "September 21, 2021"
output: html_document
---

---

### **Problem 1**

##### Problem 1.1
The moment estimator can be determined by following the Law of Large Numbers which states that the sample moment will eventually converge to the corresponding
population moment. Based on this, the first sample moment which is equivalent to the sample mean can be set equal to the first population moment, which is the expected value of the population
and can be used to find the moment estimator.

\

For the first sample moment, $k = 1$

Sample mean: $\sum_{n}^{i = 1} X_i^1 = \overline{X}$

Population mean: $E(X_i) = \frac{0 + \theta}{2} = \theta / 2$

$\overline{X} = \theta / 2$

$\theta = 2\overline{X}$

$\hat{\theta}_M = 2\overline{X}$

\

##### Problem 1.2
The PDF of the given uniform distribution is the following:

$f(0, \theta) = \begin{cases} \frac{1}{\theta}, &  0 \leq x \leq \theta,\\ 0  & \text{otherwise }\end{cases}$

Next, the likelihood function, $L(\theta)$ will be calculated by the following:

$L(\theta) = \prod_{i=1}^{n} \frac{1}{\theta} = \theta^{-n}$

Then take the derivative of the logarithmic likelihood with respect to $\theta$ to find the maximizer for $L(\theta)$

$\frac{\mathrm{d} log L(\theta)}{d\theta} = -\frac{n}{\theta}$

Finally set it equal to 0 and solve the for $\hat{\theta}_L$

$-\frac{n}{\theta} = 0$

Since the function is decreasing and if we assume that the uniformly distributed random variables follow this order: $X_1 \leq X_2 \leq ... \leq X_n$, the largest value must be taken to to maximize the likelihood.

So, $\hat{\theta}_L = X_n$
 
\

##### Problem 1.3
Taking the mean and variance of the given SRS:

```{r}
x <- c(1.0, 2.4, 3.2, 1.3, 0.5, 3.2, 6.8)
mean(x)
var(x)
```

$\hat{\theta}_M = 2\overline{X} = 2 (2.63) = 5.26$

$\hat{\theta}_K = X_n = 6.8$

In this case, $\hat{\theta}_M$ is better is it is closer to the observed variance parameter from the given SRS.

